version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    container_name: "mongo"
  gums:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    container_name: "gums"
    links:
      - mongo
  gums-ui:
    build: ./gums-ui
    ports:
      - "32769:4200"
    container_name: "gums-ui"
    links:
      - gums